- name: POC
  hosts: myhosts
  tasks:
   - name: Ping hosts
     ansible.builtin.ping:

   - name: Print message
     ansible.builtin.debug:
       msg: Hello world

   - name: Reboot machine
     become: yes
     become_method: sudo
     vars:
       ansible_become_pass: "123"
     ansible.builtin.reboot:
       reboot_command: reboot
       search_paths: [/run/current-system/sw/bin/]